### PR TITLE
Merging the rest of the course

### PR DESCRIPTION
**Pull request by hclivess**
Hello, Mike. This should be all the parts of the course reviewed, except the few one that were switched. If you add these to your online course, I can go through the final revision and fix the few missing pieces.

### CODE REVIEW

**Comment by mikeckennedy** [comment]
Wonderful! Thanks. There is one more chapter coming in a couple of days. Do you mind holding on to do that last one? It's pretty short.

**Comment by hclivess** [comment]
Yes, let's do that one too :)

**Comment by mikeckennedy** [comment]
Thanks. I'll let you know when it's online.

**Comment by mikeckennedy** [comment]
Hey, I just published transcripts for chapter 15, deployment. Could you give them a look over?

**Pull request merged**
